### ISSUE TITLE
Inconsistent capitalization of other open issues

### ISSUE THREAD

**Issue by timflannagan** [nathan-weinberg/nathan-weinberg.github.io#4]
Please fix #2

**Comment by Daniel-Pivonka** [comment]
![image](https://user-images.githubusercontent.com/22037319/54045730-58afcd80-41a0-11e9-92b9-0f454ee707aa.png)

**Comment by nathan-weinberg** [comment]
Not a part of the repo guidelines

**Comment by timflannagan** [comment]
Please add a pull request template so people that want to contribute don't violate repo guidelines.
